Insegnamenti magistrale
csunibo/informabot pull request #108
Opened 2023-09-16 19:12 UTC by bogo8liuk

Aggiunta degli insegnamenti della laurea magistrale

2023-09-17 14:40 UTC, foxyseta requested changes
I nomi degli insegnamenti mi sembrano conformi con quelli dati in precedenza. Ti ho lasciato giusto due commentini.

2023-09-17 14:40 UTC, foxyseta commented on model/parse.go
> +		fmt.Println(err)
`fmt` è il pacchetto di Go generalista per l'I/O formattato. Questo mi sembra più un messaggio che va accodato al registro, e quindi userei il pacchetto `log` (altrettanto semplice) come già fatto nel resto del progetto. Se trovi altri usi di `fmt` dovrebbe andrebbe invece usato `log` cambia pure anche quelle.

2023-09-17 14:40 UTC, foxyseta commented on json/actions.json
> +      "description": "Tutto su decision making",
I titoli degli insegnamenti in Italiano hanno la lettera maiuscola (solo sulla prima parola), quindi aggiornerei i valori dei campi `description` che hai aggiunto.

In inglese invece, i titoli (inclusi quelli degli insegnamenti) hanno le maiuscole su tutte le parole che non siano né all'inizio della frase né usate come articoli/preposizioni/congiunzioni di poche lettere. Scegli tu se vuoi adottare le convenzioni inglesi per gli insegnamenti in inglese o fingere che sia comunque italiano.

2023-09-17 16:00 UTC, foxyseta commented
@csunibo/informatica-magistrale per ogni insegnamento aggiunto da questa PR, andrebbe creata la repo corrispondente. La guida in questione è: https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/index.html.

2023-09-17 17:34 UTC, bogo8liuk commented
Aggiunte due commit:

- Uso di `log` al posto di `fmt`;
- Ho usato una sola convenzione per i titoli degli insegnamenti (quella italiana)

Per quanto riguarda i repository degli insegnamenti ik, li aggiungerò man mano (o io o gli altri moderatori delle magistrali).

2023-09-17 19:57 UTC, foxyseta approved these changes

2023-09-17 19:58 UTC, foxyseta commented
Bene! Allora aspettiamo che voi in @csunibo/informatica-magistrale aggiungiate gli insegnamenti in questione prima di accettare la PR.

https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/index.html

2023-09-18 17:43 UTC, kocierik commented
> Bene! Allora aspettiamo che voi in @csunibo/informatica-magistrale aggiungiate gli insegnamenti in questione prima di accettare la PR.
> 
> https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/index.html

ho aggiunto tutte le repo dei corsi facoltativi del primo anno (non ho controllato i nomi avendolo fatto velocemente)

2023-09-18 18:42 UTC, foxyseta commented
Grazie mille! @bogo8liuk puoi collaudare se i link ora vanno dalla tua istanza locale del bot.

2023-09-18 20:36 UTC, bogo8liuk commented
> Grazie mille! @bogo8liuk puoi collaudare se i link ora vanno dalla tua istanza locale del bot.
> 
> (Questo tipo di cose non sono coperte da quei pochi test che abbiamo ahahahah #85)

Ho controllato i vari link nel bot e, a parte didattica-del-informatica, sono tutti ok. Ho fatto una commit per fixare la gestione degli apici singoli (apostrofi) e ora funzionano tutti (didattica-del-informatica compresa). Mancano i repo del secondo anno

2023-09-19 14:39 UTC, foxyseta requested changes
Una finezza.

2023-09-19 14:39 UTC, foxyseta commented on utils/util.go
> +		if len(apostropheSplit) == 2 {
Nel caso di più apostrofi nello stesso conglomerato di parole come `dell'ultim'ora` (caso limite che non accade quasi mai nella lingua Italiana) prima aggiungevamo l'ultima parola (`ora`), e ora ignoriamo l'intero conglomerato. Mi sembra che stiamo regredendo con la nostra euristica per questo caso particolare. Se ci accontentiamo di emulare l'euristica precedente per questa casistica, penso potremmo usare `>= 2` anizché `== 2`.

2023-09-19 14:43 UTC, foxyseta commented
> > Grazie mille! @bogo8liuk puoi collaudare se i link ora vanno dalla tua istanza locale del bot.
> > (Questo tipo di cose non sono coperte da quei pochi test che abbiamo ahahahah #85)
> 
> Ho controllato i vari link nel bot e, a parte didattica-del-informatica, sono tutti ok. Ho fatto una commit per fixare la gestione degli apici singoli (apostrofi) e ora funzionano tutti (didattica-del-informatica compresa), ho lasciato un commento che spiega la logica implementata, spero si capisca. Ora mancano i repo del secondo anno

Intendi `didattica-del-informatica` o `didattica-dell-informatica`? Giusto per capire se stiamo rimuovendo la doppia apposta in questo caso o no.

Forse per le repo del secondo anno potrebbe pensarci qualcuno fra @cristian-5, @lucadonnoh, @stefanostaffolani, @AndreSkin o @MaxRondelli, siccome tu e @kocierik avete già fatto un lavorone assieme. La guida di riferimento è sempre https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/index.html.

2023-09-19 16:22 UTC, bogo8liuk commented
> > > Grazie mille! @bogo8liuk puoi collaudare se i link ora vanno dalla tua istanza locale del bot.
> > > (Questo tipo di cose non sono coperte da quei pochi test che abbiamo ahahahah #85)
> > 
> > 
> > Ho controllato i vari link nel bot e, a parte didattica-del-informatica, sono tutti ok. Ho fatto una commit per fixare la gestione degli apici singoli (apostrofi) e ora funzionano tutti (didattica-del-informatica compresa), ho lasciato un commento che spiega la logica implementata, spero si capisca. Ora mancano i repo del secondo anno
> 
> Intendi `didattica-del-informatica` o `didattica-dell-informatica`? Giusto per capire se stiamo rimuovendo la doppia apposta in questo caso o no.
> 
> Forse per le repo del secondo anno potrebbe pensarci qualcuno fra @cristian-5, @lucadonnoh, @stefanostaffolani, @AndreSkin o @MaxRondelli, siccome tu e @kocierik avete già fatto un lavorone assieme. La guida di riferimento è sempre https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/index.html.

Ho cambiato la gestione degli apostrofi perché se, come veniva fatto in precedenza, troncassimo le parole precedenti all'apostrofo (quindi, per esempio, "dell'informatica" diventa semplicemente "informatica", così come anche "l'informatica" diventa "informatica"), avremmo che verrebbe creato un link rotto per il repo `didattica-del-informatica` (ovvero `didattica-informatica`). Quindi, ho supposto che la politica fosse troncare solo il primo carattere prima di un apostrofo. Se questa mia supposizione è corretta, allora rimane da definire la politica nel caso ci sia più di un apostrofo. Se invece è errata, è necessario cambiare nome al repo `didattica-del-informatica`.

2023-09-20 01:18 UTC, foxyseta commented
> > > > Grazie mille! @bogo8liuk puoi collaudare se i link ora vanno dalla tua istanza locale del bot.
> > > > (Questo tipo di cose non sono coperte da quei pochi test che abbiamo ahahahah #85)
> > > 
> > > 
> > > Ho controllato i vari link nel bot e, a parte didattica-del-informatica, sono tutti ok. Ho fatto una commit per fixare la gestione degli apici singoli (apostrofi) e ora funzionano tutti (didattica-del-informatica compresa), ho lasciato un commento che spiega la logica implementata, spero si capisca. Ora mancano i repo del secondo anno
> > 
> > 
> > Intendi `didattica-del-informatica` o `didattica-dell-informatica`? Giusto per capire se stiamo rimuovendo la doppia apposta in questo caso o no.
> > Forse per le repo del secondo anno potrebbe pensarci qualcuno fra @cristian-5, @lucadonnoh, @stefanostaffolani, @AndreSkin o @MaxRondelli, siccome tu e @kocierik avete già fatto un lavorone assieme. La guida di riferimento è sempre https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/index.html.
> 
> Ho cambiato la gestione degli apostrofi perché se, come veniva fatto in precedenza, troncassimo le parole precedenti all'apostrofo (quindi, per esempio, "dell'informatica" diventa semplicemente "informatica", così come anche "l'informatica" diventa "informatica"), avremmo che verrebbe creato un link rotto per il repo `didattica-del-informatica` (ovvero `didattica-informatica`). Quindi, ho supposto che la politica fosse troncare solo il primo carattere prima di un apostrofo. Se questa mia supposizione è corretta, allora rimane da definire la politica nel caso ci sia più di un apostrofo. Se invece è errata, è necessario cambiare nome al repo `didattica-del-informatica`.

La politica non è mai stata troncare il primo carattere prima dell'apostrofo (non ne vedrei il motivo in realtà). Per un gusto estetico al tempo piaceva rimuovere le paroline prima degli apostrofi perché poco importanti. Qunindi "Logica per l'informatica" è diventato "logica-per-informatica" non perché volessimo togliere una sola lettera prima dell'apostrofo, ma perché non piaceva `logica-per-l-informatica`, che a me invece è sempre piaciuto. In questo caso il boto dovrebbe correttamente generare `didattica-informatica` dal nome dell'insegnamento "Didattica dell'informatica", e se @kocierik ha chiamato la repo diversamente andrebbe rinominata.

Ovviamente tutto questo ammesso non vogliamo cambiare politica su nulla. Del resto, la convenzione di eliminazione delle parole pre-apostrofo non è mai stata documentata.

Quindi la prima domanda è: `logica-per-l-informatica` (il link vecchio si rompe così) e `didattica-dell-informatica` o `logica-per-informatica` e `didattica-informatica`?

2023-09-20 18:48 UTC, bogo8liuk commented
> > > > > Grazie mille! @bogo8liuk puoi collaudare se i link ora vanno dalla tua istanza locale del bot.
> > > > > (Questo tipo di cose non sono coperte da quei pochi test che abbiamo ahahahah #85)
> > > > 
> > > > 
> > > > Ho controllato i vari link nel bot e, a parte didattica-del-informatica, sono tutti ok. Ho fatto una commit per fixare la gestione degli apici singoli (apostrofi) e ora funzionano tutti (didattica-del-informatica compresa), ho lasciato un commento che spiega la logica implementata, spero si capisca. Ora mancano i repo del secondo anno
> > > 
> > > 
> > > Intendi `didattica-del-informatica` o `didattica-dell-informatica`? Giusto per capire se stiamo rimuovendo la doppia apposta in questo caso o no.
> > > Forse per le repo del secondo anno potrebbe pensarci qualcuno fra @cristian-5, @lucadonnoh, @stefanostaffolani, @AndreSkin o @MaxRondelli, siccome tu e @kocierik avete già fatto un lavorone assieme. La guida di riferimento è sempre https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/index.html.
> > 
> > 
> > Ho cambiato la gestione degli apostrofi perché se, come veniva fatto in precedenza, troncassimo le parole precedenti all'apostrofo (quindi, per esempio, "dell'informatica" diventa semplicemente "informatica", così come anche "l'informatica" diventa "informatica"), avremmo che verrebbe creato un link rotto per il repo `didattica-del-informatica` (ovvero `didattica-informatica`). Quindi, ho supposto che la politica fosse troncare solo il primo carattere prima di un apostrofo. Se questa mia supposizione è corretta, allora rimane da definire la politica nel caso ci sia più di un apostrofo. Se invece è errata, è necessario cambiare nome al repo `didattica-del-informatica`.
> 
> La politica non è mai stata troncare il primo carattere prima dell'apostrofo (non ne vedrei il motivo in realtà). Per un gusto estetico al tempo piaceva rimuovere le paroline prima degli apostrofi perché poco importanti. Qunindi "Logica per l'informatica" è diventato "logica-per-informatica" non perché volessimo togliere una sola lettera prima dell'apostrofo, ma perché non piaceva `logica-per-l-informatica`, che a me invece è sempre piaciuto. In questo caso il boto dovrebbe correttamente generare `didattica-informatica` dal nome dell'insegnamento "Didattica dell'informatica", e se @kocierik ha chiamato la repo diversamente andrebbe rinominata.
> 
> Ovviamente tutto questo ammesso non vogliamo cambiare politica su nulla. Del resto, la convenzione di eliminazione delle parole pre-apostrofo non è mai stata documentata.
> 
> Quindi la prima domanda è: `logica-per-l-informatica` (il link vecchio si rompe così) e `didattica-dell-informatica` o `logica-per-informatica` e `didattica-informatica`?

Direi di troncare la parola prima dell'apostrofo (come veniva fatto in precedenza). Faccio rollback.

2023-09-20 19:12 UTC, bogo8liuk commented
Purtroppo non ho i permessi per cambiare nome al repo https://github.com/csunibo/didattica-del-informatica

2023-09-20 19:18 UTC, lucadonnoh commented
a regà a lavoro se faccio una PR con così tanti commenti licenziano me e tutti quelli che hanno commentato

https://en.m.wikipedia.org/wiki/Law_of_triviality

2023-09-20 22:04 UTC, foxyseta commented
> Purtroppo non ho i permessi per cambiare nome al repo https://github.com/csunibo/didattica-del-informatica

Hai ragione! @kocierik: nella guida è specificato che i permessi devono essere "Mantain", ma tu in questo caso hai messo "Read".

@bogo8liuk: l'ho rinominata io, ma in condizioni normali avrai i permessi di farlo in autonomia per gli insegnamenti che ti competono. Ho aggiornato il nome anche sulla repo config: https://github.com/csunibo/config/pull/4/commits/8565a0dfaa61fb184f07b0369e835071f25093ce

@lucadonnoh non avere collegamenti rotti nel bot è importante. Scegliere i nomi è un arte. Fila a rispondere negli altri posti in cui ti ho taggato (possibilmente in modo costruttivo)!

2023-09-20 22:07 UTC, foxyseta approved these changes
Io mergerei e mettrei in produzione quando ho tempo. Il resto dei compiti collegati è il correggere le autorizzazioni sulle repo e ci può pensare @kocierik.

2023-09-21 11:07 UTC, merged