Tag manteiner
csunibo/informabot pull request #132
Opened 2023-11-17 18:58 UTC by Jabbar03

2023-11-17 19:01 UTC, ali-benny commented
In realtà, come scritto in #93 sarebbe più pratico che si inoltrasse automaticamente il messaggio in cui ci hanno taggato sul gruppo csunibo

2023-11-17 19:06 UTC, musianisamuele commented
> In realtà, come scritto in #93 sarebbe più pratico che si inoltrasse automaticamente il messaggio in cui ci hanno taggato sul gruppo csunibo

Giustamente sarebbe più efficace in quanto non è detto che i maintainers siano in tutti i gruppi con il bot. Il fatto è che @csunibo indica già il nome del gruppo quindi il bot interverrebbe tutte le volte che si indica semplicemente il gruppo. Per risolvere si potrebbe inverare un altro tag o propriamente un comando (tipo /issue) che inoltra direttamente la il messaggio citato

2023-11-17 19:24 UTC, musianisamuele commented
Inoltre inoltrare un messaggio sul gruppo di csunibo riporta al problema di hardcodare gli I'd dei gruppi all'interno del bot.

In realtà non credo sia un problema perché csunibo dovrebbe essere un gruppo statico che non cambia di anno in anno come quelli relativi ai vari anni

2023-11-17 19:41 UTC, foxyseta commented
Anche io sono a favore di usare la sintassi @ anziché /. La prima non è idiomatica, ha l'effetto collaterale di aprire la chat anziché rinviare il comando quando toccata da GUI e cosa più grave richiede che il bot abbia accesso in visualizzazione a tutti i messaggi della chat (non solo quelli che cominciano con /), cosa che è un privilegio non richiesto.

Ma se vogliamo inoltrare il messaggio a quel punto non è molto più pratico usare `/csunibo` e poi si apre il gruppo e ci scrive direttamente l'utente? Così possiamo sostenere una conversazione vera e propria.

2023-11-17 19:50 UTC, foxyseta commented
Forse il vantaggio di taggare direttamente dentro il gruppo originario è quello che si può osservare l'incidente a colpo d'occhio, ma è vero che non diamo garanzie di essere già dentro ai gruppi.

2023-11-17 20:11 UTC, musianisamuele commented
Non ho controllato le API ma forse c'è un metodo per vedere se un utente è dentro un gruppo. Si potrebbe fare che di predefinito si tagga e se nessuno è in quel gruppo si inoltra il messaggio

2023-11-17 21:13 UTC, foxyseta commented
Sicuramente un modo c'è sì. Però anziché inoltrare il messaggio penso sia meglio taggare @csunibo come piano B chiedendo di scrivere lì. Così abbiamo modo di fare domande di contesto subito

2023-11-18 10:29 UTC, musianisamuele commented
Ok direi allora che introduciamo un comando /issue che tagga i maintainers, se nessuno di quelli che verrebbe taggato è presente nel gruppo scriviamo di inoltrare il pronome a @csunibo.

Che ne dite?

2023-11-18 10:29 UTC, musianisamuele commented
Ok direi allora che introduciamo un comando /issue che tagga i maintainers, se nessuno di quelli che verrebbe taggato è presente nel gruppo scriviamo di inoltrare il pronome a @csunibo.

Che ne dite?

2023-11-18 11:08 UTC, foxyseta commented
Perfetto.Scusa @Jabbar03! Se vuoi la prossima volta puoi scrivere sulla issue su cui vorresti lavorare per chiedere più informazioni.

2023-11-18 19:51 UTC, musianisamuele commented
@Jabbar03 al lavoro adesso per modificare la PR

2023-11-19 00:01 UTC, foxyseta commented
La cosa più importante è fare 0 hardcoding per me (NESSUN handle Telegram dentro i file .go). Se riesci io mettrei tutto in `actions.json`. Probabilmente ti servirà l'aiuto di qualche senpai tipo @bogo8liuk, @musianisamuele o me.

2023-11-19 01:27 UTC, Jabbar03 commented
Ok mi metto al lavoro. Se ho domande chiedo ai senpai citati.

2023-11-24 17:45 UTC, foxyseta commented
Il primo controllo come hai notato falisce solo perché vuole che formatti il codice prima che la PR venga accettata. Se il secondo continua a fallire non preoccuparti ci guardo io alla fine.

2023-11-24 21:05 UTC, musianisamuele requested changes
Ci sono un po' di cosa da cambiare

2023-11-24 21:05 UTC, musianisamuele commented on model/globals.go
> +		log.Fatalf("Error reading mantainer.json file: %s", err.Error())
Il file si chiama `maintainerS.json` :)

2023-11-24 21:05 UTC, musianisamuele commented on model/parse.go
> +		return nil, fmt.Errorf("error reading groups.json file: %w", err)
Perché si fa riferimento al file `groups.json`? Errore di copia-incolla?

2023-11-24 21:05 UTC, musianisamuele commented on model/parse.go
> +		return mantainer, nil
Non mi piace troppo come è gestito qui l'errore. Perché se il file non esiste viene restituito l'array vuoto e può causare confusione nel debug. Io restituirei proprio un errore sul fatto che il file non è stato trovato.

2023-11-24 22:12 UTC, Jabbar03 commented on model/controller.go
> +		s.WriteString("Scrivete sul gruppo di @csunibo nel topic Bot")
difficile spostare la risposta nel json dei mantainers
provo a spostarla in un altro json magari posso provare in quello delle action come campo response nel comando issue

2023-11-24 22:15 UTC, Jabbar03 commented on model/controller.go
> +	answer.WriteString("Mantainer c'è bisogno del vostro aiuto" + "\n")
o la risolvo come ho proposto sopra oppure sono dell'avviso di togliere completamente questa risposta.
preferisco che siano taggati i mantainer del gruppo e basta. 
Tanto se è stato invocato il comando e taggati i mantainer in questione è chiaro che ci sia bisogno di loro.
Per citare qualcuno, questa stringa è più che altro zucchero sintattico.

2023-11-24 22:15 UTC, Jabbar03 commented on model/globals.go
> +		log.Fatalf("Error reading mantainer.json file: %s", err.Error())
mb

2023-11-24 22:15 UTC, Jabbar03 commented on model/controller.go
> +	for i, participant := range utils.GetChatMembers(bot, chatID, Ids) {
ok

2023-11-24 22:15 UTC, Jabbar03 commented on model/controller.go
> +	var Ids []int64
ok

2023-11-24 22:16 UTC, Jabbar03 commented on json/actions.json
> +      "description": "C'è un problema tecnico/tattico, portalo all'attenzione di un mantainer"
non viene mai stampata, riscrivo la description.

2023-11-25 09:36 UTC, ali-benny commented on json/actions.json
> +      "description": "C'è un problema tecnico/tattico, portalo all'attenzione di un mantainer"
Dovrebbe essere visualizzata nel comando /help che lista i comandi con descrizione

2023-11-25 12:13 UTC, musianisamuele commented on model/controller.go
> +		s.WriteString("Scrivete sul gruppo di @csunibo nel topic Bot")
Si esatto, andrebbe spostata nel file `actions.json`

2023-11-25 12:17 UTC, musianisamuele commented on model/controller.go
> +	answer.WriteString("Mantainer c'è bisogno del vostro aiuto" + "\n")
No io invece la lascerei, non mi dispiace che sia esplicitato il motivo del tag. Questo perché se ricevi un tag in una notifica almeno sai che è associato al messaggio del bot e non ad un tag generico da parte di un utente. Ovviamente la lascerei ma non in quel punto, andrebbe spostata nel file `actions.json`.

Poi cosa c'entra lo zucchero sintattico? Mi sa che ti stai confondendo sui termini ahahah

2023-11-25 12:18 UTC, musianisamuele commented on json/actions.json
> +      "description": "C'è un problema tecnico/tattico, portalo all'attenzione di un mantainer"
> Dovrebbe essere visualizzata nel comando /help che lista i comandi con descrizione

Giusto, mi ero scordato di `/help`

2023-11-25 22:23 UTC, musianisamuele commented
Adesso faccio la review, però non capisco perché i test falliscano. @foxyseta te hai qualche idea. Quello sul formatting di go a me in locale non da alcun tipo di problema

2023-11-25 22:30 UTC, musianisamuele requested changes
Tralasciando i test che non passano c'è solo la questione di come scrivere il campo data

2023-11-25 22:30 UTC, musianisamuele commented on model/globals.go
> +		log.Fatalf("Error reading mantainers.json file: %s", err.Error())
Io qui scriverei "Error parsing mantainers...". Però è una cosa abbastanza insignificante

2023-11-25 22:30 UTC, musianisamuele commented on json/actions.json
> +      ]
Come già detto anche in privato non mi piace questo modo di usare gli array per elencare le possibili risposte perché è molto fragile. Tu conosci la risposta giusta soltanto in base all'indice dell'array, che se per caso cambia tutto il codice si rompe. Una soluzione a mio avviso più pulita sarebbe la seguente:
```suggestion
      "response": "Mantainers, c'è bisogno del vostro aiuto \n",
      "fallback": "Nessun mantainer è presente in questo gruppo. Riportate il problema direttamente sul gruppo di @csunibo nel topic Bot"
```
Ha cambiato anche leggermente le risposte per renderle un file più chiare

2023-11-25 22:31 UTC, musianisamuele commented
Comunque per chiunque faccia il merge finale, per favore facciamo uno squash che siamo già a 20 commit per 80 righe di codice, sono 1 commit ogni 4 righe ahaha

2023-11-25 23:18 UTC, merged