Lezioni per generici corsi di laurea
csunibo/informabot pull request #138
Opened 2023-11-20 18:47 UTC by boozec

Questa PR aggiunge la possibilità di avere le lezioni per qualsiasi corso di laurea. Tengo in Draft perché ci sto lavorando ancora su. Una volta finito basterà inserire i file di configurazione che fanno il map dei corsi di laurea che si vogliono supportare ai loro link.
Inoltre aggiunge la gestione delle callback.

Resolves https://github.com/csunibo/informabot/issues/122

2023-11-21 17:17 UTC, foxyseta commented
Il test fallisce perché non hai formattato il tuo nuovo json (il progetto usa prettier). Dubbio di nomenclatura: CDLS lo fa sembrare un po' un clone di `json/config/degrees.json` (se non lo vedi forse devi fare un rebase da `main` e aggiornare i sottomoduli).

2023-11-21 18:42 UTC, boozec commented
> Il test fallisce perché non hai formattato il tuo nuovo json (il progetto usa prettier). Dubbio di nomenclatura: CDLS lo fa sembrare un po' un clone di `json/config/degrees.json` (se non lo vedi forse devi fare un rebase da `main` e aggiornare i sottomoduli).

Pensavo a `timetable.json` o `lectures.json`, che dici?

2023-11-22 01:20 UTC, foxyseta commented
`timetables.json` mi piace. Magari lo traslocherei nel sottomodulo `csunibo/config` siccome sono informazioni potenzialmente utili anche ad altre repo

2023-11-24 10:59 UTC, boozec commented
Ho aggiunto anche i test. Bisogna giusto inserire le modifiche di https://github.com/csunibo/config/pull/25, fare un check generale degli altri corsi e revisionare il codice :) Tolgo la bozza :tada:

2023-11-24 11:10 UTC, foxyseta commented
Accettata la PR citata. Dovresti poter inserire le modifiche senza problemi ora. Hai collaudato gli altri CdL anche a mano?

2023-11-24 20:59 UTC, boozec commented
> Hai collaudato gli altri CdL anche a mano?

Sì

2023-11-25 00:45 UTC, foxyseta requested changes

2023-11-25 00:45 UTC, foxyseta commented on json/actions.json
> +      "description": "Orari lezioni"
Anche se non abbiamo al momento in programma di localizzare il bot in inglese (per chi studia AI in tale lingua), penso sia comunque una buona abitudine mantenere separata logica e stringhe da inviare come messaggio. Per questo motivo, non rimuoverei i campi "title" e "fallbackText" (puoi inserire i segnaposto dentro a "title" siccome hai generalizzato a vari giorni/curricula/anni).

2023-11-27 21:23 UTC, foxyseta approved these changes

2023-11-27 21:24 UTC, merged